credentials:
  ALIBABA_CLOUD_ACCESS_KEY_ID: "add ALIBABA_CLOUD_ACCESS_KEY_ID"
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: "add ALIBABA_CLOUD_ACCESS_KEY_SECRET here"

api:
  ENDPOINT: oss-cn-beijing.aliyuncs.com
  BUCKET_NAME: hussain

models:
  MODEL1: weights/model1.pt
  MODEL2: weights/model2.pt

video:
  OUTPUT_VIDEO_PATH: output_video.mov
  SIMILARITY_THRESHOLD: 0.7
  CODEC_FORMAT: 'MP4V'

email:
  EMAIL_REG: r'[\\w\\.-]+@[\\w\\.-]+(?:\\.[\\w]+)+'
