credentials:
  ALIBABA_CLOUD_ACCESS_KEY_ID: LTAI5tE1rynpnVmyaUhkb5BB
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: xlXLOddRWuTS4Qm6iGgyKA5NplksIQ

api:
  ENDPOINT: oss-cn-beijing.aliyuncs.com
  BUCKET_NAME: hussain

model:
  MODEL_PATH: runs/classify/train17/weights/best.pt

video:
  OUTPUT_VIDEO_PATH: output_video.mov
  SIMILARITY_THRESHOLD: 0.7
  CODEC_FORMAT: 'MP4V'

email:
  EMAIL_REG: r'[\w\.-]+@[\w\.-]+(?:\.[\w]+)+'
